# Generated by Django 2.0 on 2019-04-24 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('desc', models.TextField(max_length=1000, verbose_name='描述')),
                ('count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2019, 4, 25, 1, 10, 32, 327453), verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '新闻活动',
                'verbose_name_plural': '新闻活动',
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='图片名称')),
                ('file', models.FileField(upload_to='mews/%Y_%m', verbose_name='图片路径')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '活动图片',
                'verbose_name_plural': '活动图片',
            },
        ),
        migrations.CreateModel(
            name='Praise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News', verbose_name='所属活动')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
            },
        ),
    ]
