# Generated by Django 2.0 on 2019-05-03 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190503_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 18, 49, 3, 362587), verbose_name='发布时间'),
        ),
    ]
