# Generated by Django 2.0 on 2019-05-05 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190503_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 5, 13, 16, 47, 555813), verbose_name='发布时间'),
        ),
    ]
