# Generated by Django 2.0 on 2019-05-07 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190505_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 7, 19, 3, 0, 230914), verbose_name='发布时间'),
        ),
    ]
