# Generated by Django 2.0 on 2019-05-08 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190508_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 22, 55, 59, 232185), verbose_name='发布时间'),
        ),
    ]
