# Generated by Django 2.0 on 2019-05-09 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20190508_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 9, 15, 37, 1, 700605), verbose_name='发布时间'),
        ),
    ]
