# Generated by Django 2.0 on 2019-05-11 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20190509_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 11, 8, 57, 696924), verbose_name='发布时间'),
        ),
    ]
