# Generated by Django 2.0 on 2019-04-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
        migrations.AlterField(
            model_name='register',
            name='no',
            field=models.CharField(max_length=30, unique=True, verbose_name='所属班级编号'),
        ),
    ]
