# Generated by Django 2.0 on 2019-05-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='apply_data',
            field=models.FileField(blank=True, null=True, upload_to='apply/%Y_%m', verbose_name='申请材料路径'),
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='title',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='申请理由'),
        ),
    ]
