# Generated by Django 2.0 on 2019-04-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190411_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='no',
            field=models.CharField(max_length=30, verbose_name='所属班级编号'),
        ),
    ]
