# Generated by Django 2.0 on 2019-05-03 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190503_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyrecord',
            old_name='title',
            new_name='content',
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='obj_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='申请对象id'),
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='deal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealuser', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='users',
            field=models.ManyToManyField(related_name='many_user', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
    ]
