# Generated by Django 2.0 on 2019-05-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190503_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='申请理由'),
        ),
    ]
