# Generated by Django 2.0 on 2019-04-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190411_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='register',
            name='no',
            field=models.CharField(max_length=30, verbose_name='所属编号'),
        ),
        migrations.AlterField(
            model_name='register',
            name='sno',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='学号/工号'),
        ),
    ]
