# Generated by Django 2.0 on 2019-05-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190503_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyrecord',
            name='users',
        ),
    ]
