# Generated by Django 2.0 on 2019-04-11 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190411_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyrecord',
            name='users',
            field=models.ManyToManyField(related_name='many_user', to=settings.AUTH_USER_MODEL, verbose_name='发送人'),
        ),
    ]
