# Generated by Django 2.0 on 2019-04-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_applyrecord_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
