# Generated by Django 2.0 on 2019-05-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190505_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='type',
            field=models.IntegerField(choices=[(0, '申请加入社团'), (1, '申请发布资料'), (2, '申请发布项目'), (3, '申请创建社团')], default=0, verbose_name='申请类型'),
        ),
    ]
