# Generated by Django 2.0 on 2019-05-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190507_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='type',
            field=models.IntegerField(choices=[(0, '申请加入社团'), (1, '申请创建社团')], default=0, verbose_name='申请类型'),
        ),
    ]
