# Generated by Django 2.0 on 2019-05-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190508_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='apply_data',
            field=models.FileField(default='', upload_to='apply/%Y_%m', verbose_name='申请材料路径'),
        ),
    ]
