# Generated by Django 2.0 on 2019-05-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_applyrecord_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='type',
            field=models.IntegerField(choices=[(0, '申请加入社团'), (1, '申请创建社团'), (2, '申请退出社团')], default=0, verbose_name='申请类型'),
        ),
    ]
