# Generated by Django 2.0 on 2019-04-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190411_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='分类名称'),
        ),
    ]
