# Generated by Django 2.0 on 2019-04-24 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='apply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papplyuser', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='project',
            name='pub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubuser', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
    ]
