# Generated by Django 2.0 on 2019-05-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190427_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, '悬赏中'), (1, '已承接'), (2, '已完成'), (3, '未处理'), (4, '未通过')], default=3, verbose_name='项目状态'),
        ),
    ]
