# Generated by Django 2.0 on 2019-04-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='公告标题')),
                ('desc', models.CharField(max_length=200, verbose_name='公告内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '社团公告',
                'verbose_name_plural': '社团公告',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30, unique=True, verbose_name='社团编号')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='社团名称')),
                ('objective', models.CharField(max_length=200, verbose_name='社团宗旨')),
                ('image', models.FileField(default='default/community.png', upload_to='community/%Y_%m')),
                ('desc', models.TextField(default='这个社团的人很懒，什么都没留下', max_length=500, verbose_name='社团描述')),
                ('community_type', models.IntegerField(choices=[(1, '学习类'), (2, '语言类'), (3, '艺术类'), (4, '户外类'), (5, '体育类'), (6, '其他')], default=6, verbose_name='社团类型')),
                ('plan_count', models.IntegerField(default=0, verbose_name='计划人数')),
                ('real_count', models.IntegerField(default=0, verbose_name='实际人数')),
                ('is_dalete', models.BooleanField(default=False, verbose_name='删除')),
                ('score', models.IntegerField(default=100, verbose_name='社团积分')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建社团日期')),
                ('dis_date', models.DateTimeField(blank=True, null=True, verbose_name='解散社团日期')),
            ],
            options={
                'verbose_name': '社团信息',
                'verbose_name_plural': '社团信息',
            },
        ),
        migrations.CreateModel(
            name='CommunityFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='文件名称')),
                ('file', models.FileField(default='', upload_to='community_fille/%Y_%m', verbose_name='文件路径')),
                ('community_file_type', models.IntegerField(choices=[(0, '社团导师简历'), (1, '社团简章'), (2, '社团规章制度'), (3, '其他')], default=3, verbose_name='文件类型')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community', verbose_name='所属社团')),
            ],
            options={
                'verbose_name': '社团相关文件',
                'verbose_name_plural': '社团相关文件',
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='荣誉名称')),
                ('date', models.DateTimeField(verbose_name='荣誉获取时间')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community', verbose_name='所属社团')),
            ],
            options={
                'verbose_name': '社团荣誉',
                'verbose_name_plural': '社团荣誉',
            },
        ),
        migrations.CreateModel(
            name='RecentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='主题')),
                ('file', models.FileField(default='', upload_to='community_recent_plan/%Y_%m', verbose_name='近期规划文件')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community', verbose_name='所属社团')),
            ],
            options={
                'verbose_name': '社团近期规划',
                'verbose_name_plural': '社团近期规划',
            },
        ),
    ]
