# Generated by Django 2.0 on 2019-04-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20190412_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentplan',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
